### ISSUE TITLE
[BUG] Incorrect metadata canonical URL with next-intl

### ISSUE THREAD

**Issue by enterwiz** [opennextjs/opennextjs-cloudflare#774]
### Describe the bug

When using next-intl in `as-needed` mode, the `canonical` URL in metadata shows the correct path (`https://mysite.com`) during `next dev`, but incorrectly appends the default locale (`/en`) during `next preview` or production builds. This violates the `as-needed` mode specification where default locales shouldn't appear in URLs.

### Steps to reproduce

1. Create a Next.js project with nextjs, opennextjs and next-intl (v3+)
2. Configure i18n with `as-needed` mode:

```typescript
   // middleware.ts
   export default createMiddleware({
     locales: ['en', 'zh'],
     defaultLocale: 'en',
     localePrefix: 'as-needed'
   });
```

3. Set metadata with relative canonical:

```
// app/[locale]/layout.tsx
const metadata: Metadata = {
  metadataBase: new URL('https://mysite.com'),
  alternates: { canonical: './' }
};
```

4. Run `next dev` → Open /en → Canonical shows https://mysite.com (correct)
5. Run `opennextjs-cloudflare build && opennextjs-cloudflare preview` → Open /en → Canonical shows https://mysite.com/en (incorrect)

### Expected behavior

Expected behavior​​

Canonical URL should consistently omit default locale prefixes in as-needed mode across all environments:

- Dev: https://mysite.com
- Preview/Production: https://mysite.com

### @opennextjs/cloudflare version

1.0.4

### Wrangler version

4.19.1

### next info output

```shell
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.5.0: Tue Apr 22 19:53:27 PDT 2025; root:xnu-11417.121.6~2/RELEASE_ARM64_T6041
  Available memory (MB): 24576
  Available CPU cores: 12
Binaries:
  Node: 22.11.0
  npm: 10.9.0
  Yarn: N/A
  pnpm: 10.8.0
Relevant Packages:
  next: 15.3.3 // There is a newer version (15.3.5) available, upgrade recommended! 
  eslint-config-next: 15.3.3
  react: 19.1.0
  react-dom: 19.1.0
  typescript: 5.8.3
Next.js Config:
  output: N/A
 ⚠ There is a newer version (15.3.5) available, upgrade recommended! 
   Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
   Read more - https://nextjs.org/docs/messages/opening-an-issue
```

**Comment by vicb** [comment]
It looks like you are using a relatively old version of the adapter.
Chances are that this is already fixed in the latest version.
Please give it a try.

**Comment by seatayu** [comment]
> It looks like you are using a relatively old version of the adapter. Chances are that this is already fixed in the latest version. Please give it a try.

upgrade @opennextjs/cloudflare to 1.4.0, the problem still exists.

@opennextjs/cloudflare: 1.4.0
@cloudflare/workers-types: 4.20250711.0
wrangler: 4.24.3

**Comment by vicb** [comment]
Please attach a minimal repro (link to a GH repo) and then you can re-open the issue.
Thanks!

**Comment by seatayu** [comment]
> Please attach a minimal repro (link to a GH repo) and then you can re-open the issue. Thanks!

Hi! I created a project for test this scenario.

https://github.com/enterwiz/opennext-canonical-test

`@opennextjs/cloudflare` is upgraded to 1.5.1

When using `npm run dev`, all the canonical of the paths below are correct. However, using `npm run preview`, the canonical is wrong when changing to the default en locale (with unexpected `/en` prefix).

Please check these URLs:

| URL Path | Expect Canonical | Actual Canonical | is i18n route | is correct |
|---|---|---|---|---|
| / | http://localhost:8787/ | http://localhost:8787/en | Yes | No |
| /without-i18n | http://localhost:8787/without-i18n | http://localhost:8787/without-i18n | No | Yes |
| /with-i18n | http://localhost:8787/with-i18n | http://localhost:8787/en/with-i18n | Yes | No |
| /de/with-i18n | http://localhost:8787/de/with-i18n | http://localhost:8787/de/with-i18n | Yes | Yes |

**Comment by sommeeeer** [comment]
I took a look at this and indeed the canonical is showing `/en`  when it should not. The `createMiddleware` from `next-intl` will return a rewrite with `x-middleware-rewrite: 'http://localhost:8787/en'`. Since rewrites as of now will have the wrong `request.url` (see this related [issue](https://github.com/opennextjs/opennextjs-aws/issues/848)) the canonical computed on the destination will not be correct in the rendered HTML.

I tested this repo running OpenNext [locally](https://opennext.js.org/aws/contribute/local_run) with the AWS adapter with this [PR](https://github.com/opennextjs/opennextjs-aws/pull/928) which is in draft mode here, and it seemes to solve the issue there. 

However, that fix PR doesn't solve rewrites in this adapter. Im not sure what the reason for this is yet, but for some reason `routingResult.initialURL` [here](https://github.com/opennextjs/opennextjs-aws/blob/1f00712f6201ea2ea7ab27c38bfe196b458ebcb5/packages/open-next/src/core/requestHandler.ts#L271) is of the destination of the rewrite (i.e `http://localhost:8787/en`) and not the originally requested url. 

Edit: I think the reason for rewrites not working here is because this adapter is using external middleware. Therefor we might have to change this [line](https://github.com/opennextjs/opennextjs-aws/blob/1f00712f6201ea2ea7ab27c38bfe196b458ebcb5/packages/open-next/src/core/requestHandler.ts#L271) in that PR to 
```ts
// needs investigation
const reqUrl = new URL(globalThis.openNextConfig.middleware?.external ? routingResult.internalEvent.headers[INTERNAL_HEADER_INITIAL_URL] : routingResult.initialURL);
```

Next-Intl docs: https://next-intl.dev/docs/routing#locale-prefix-as-needed
Related issue: https://github.com/opennextjs/opennextjs-aws/issues/848

**Comment by sommeeeer** [comment]
@enterwiz This one will be solved on Next `15.4` thanks to this [PR](https://github.com/opennextjs/opennextjs-aws/pull/928) once `15.4` is supported by this adapter. That PR will fix `request.url` to be correct in rewrites, thus solving the issue here aswell.

We can keep the issue open until then.

**Comment by sommeeeer** [comment]
@enterwiz This should be fixed in `@opennextjs/cloudflare@1.6.4` if you use `next >= 15.4`. I'll close this for now, but feel free to re-open it if theres still issues.
